#!/usr/bin/env bash

# Link dotfiles
ln -sfv $HOME/.dotfiles/.vim ~
ln -sfv $HOME/.dotfiles/.bin ~
ln -sfv $HOME/.dotfiles/.pip ~
ln -sfv $HOME/.dotfiles/.zshenv ~
ln -sfv $HOME/.dotfiles/.curlrc ~
ln -sfv $HOME/.dotfiles/.tmux.conf ~
ln -sfv $HOME/.dotfiles/.gitconfig ~

# Update all packages and install essentials
sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y \
    build-essential \
    libgd-dev \
    libxslt-dev \
    libgeoip-dev \
    libssl-dev \
    ncurses-dev \
    libevent-dev \
    libpcre++-dev \
    zsh \
    git \
    autogen \
    autoconf \
    libtool \
    bison \
    cmake \
    silversearcher-ag

# Change default shell to ZSH for user and root
chsh -s /usr/bin/zsh
sudo chsh -s /usr/bin/zsh

# Allow SSH
sudo ufw allow ssh
sudo ufw enable

# Change Date & Time
sudo dpkg-reconfigure tzdata
