#!/usr/bin/env bash

# Unminimize Ubuntu
unminimize

# Update all packages and install essentials
apt-get update && apt-get upgrade && apt-get install -y \
    build-essential \
    libgd-dev \
    libxslt-dev \
    libgeoip-dev \
    libssl-dev \
    ncurses-dev \
    libevent-dev \
    libpcre++-dev \
    zsh \
    git \
    wget \
    dialog \
    autogen \
    tzdata \
    man-db \
    bison \
    autoconf \
    libtool \
    locales

# Change default shell to ZSH for user and root
chsh -s /usr/bin/zsh

dpkg-reconfigure tzdata
dpkg-reconfigure locales
