#!/usr/bin/env bash

# Link dotfiles
ln -sfv $HOME/.dotfiles/.vim ~
ln -sfv $HOME/.dotfiles/.bin ~
ln -sfv $HOME/.dotfiles/.pip ~
ln -sfv $HOME/.dotfiles/.zshenv ~
ln -sfv $HOME/.dotfiles/.curlrc ~
ln -sfv $HOME/.dotfiles/.tmux.conf ~
ln -sfv $HOME/.dotfiles/.screenrc ~
ln -sfv $HOME/.dotfiles/.gitconfig ~

# Make some dirs
mkdir $HOME/.vim/undo
mkdir $HOME/.dev

# Copy SSH settings
cp $HOME/.dotfiles/.config/ssh_config $HOME/.ssh
