#!/usr/bin/env bash

VERSION="2.2.0"

wget https://github.com/cli/cli/releases/download/v"$VERSION"/gh_"$VERSION"_linux_amd64.deb
dpkg -i gh_"$VERSION"_linux_amd64.deb
rm -rf gh_"$VERSION"_linux_amd64.deb

gh auth login
