#!/usr/bin/env bash

# Install mosh
git clone https://github.com/mobile-shell/mosh && cd mosh && gh pr checkout 1104 && ./autogen.sh && ./configure && make && sudo make install

# Open ports for connection
sudo ufw allow 60000:61000/udp

# Remove mosh folder
rm -rf mosh/
