#!/usr/bin/env bash

VERSION="2.4.3"

wget https://github.com/caddyserver/caddy/releases/download/v"$VERSION"/caddy_"$VERSION"_linux_amd64.tar.gz
if [ -f /.dockerenv ]; then
    tar -C /usr/local/bin -xzf caddy_"$VERSION"_linux_amd64.tar.gz
else
    sudo tar -C /usr/local/bin -xzf caddy_"$VERSION"_linux_amd64.tar.gz
fi
rm -rfi caddy_"$VERSION"_linux_amd64.tar.gz
