#!/usr/bin/env bash

wget https://github.com/gohugoio/hugo/releases/download/v0.85.0/hugo_extended_0.85.0_Linux-64bit.tar.gz
sudo tar -C /usr/local/bin -xzf hugo_extended_0.85.0_Linux-64bit.tar.gz
rm -rf hugo_extended_0.85.0_Linux-64bit.tar.gz
