#!/usr/bin/env bash

git clone --depth=1 https://github.com/vim/vim.git $HOME/vim
cd $HOME/vim || return
./configure \
	--with-features=huge \
	--enable-multibyte \
	make
sudo make install
cd && sudo rm -rfv $HOME/vim
