#!/usr/bin/env bash

VERSION=1.3.0-pre8

wget https://anti.teamidiot.de/static/nei/irssi-"$VERSION".tar.xz
tar -xzf irssi-"$VERSION".tar.xz
cd irssi-"$VERSION" || return
meson Build -Dwith-proxy=yes -Dwith-bot=yes -Denable-true-color=yes
ninja -C Build
sudo ninja -C Build install
