#!/usr/bin/env bash

VERSION="1.3.2-an"
IRSSI="irssi-$VERSION"

sudo apt update && sudo apt install -y tcl-tls \
    libsqlite3-tcl \
    tcllib \
    libperl-dev \
    meson \
    libgcrypt-dev \
    libotr5-dev \
    libglib2.0-dev

wget https://anti.teamidiot.de/static/nei/irssi-"$VERSION".tar.xz -P "$HOME"
cd "$HOME" || return
tar -C "$HOME" -xvf "$IRSSI".tar.xz
cd "$HOME"/"$IRSSI" || return
meson Build -Dwith-proxy=yes -Dwith-bot=yes -Denable-true-color=yes
ninja -C Build
sudo ninja -C Build install
