#!/usr/bin/env bash

VERSION="1.17.7"

wget https://golang.org/dl/go$VERSION.linux-amd64.tar.gz

if [ -f /.dockerenv ]; then
    tar -C /usr/local -xzf go$VERSION.linux-amd64.tar.gz
    rm -rfi go$VERSION.linux-amd64.tar.gz
else
    sudo tar -C /usr/local -xzf go$VERSION.linux-amd64.tar.gz
    sudo rm -rfi go$VERSION.linux-amd64.tar.gz
fi
