#!/usr/bin/env bash

# Install Java runtime
sudo apt-get install -y openjdk-8-jre-headless

# Add repository to apt
sudo wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
sudo echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list

# Update & Install
sudo apt-get update
sudo apt-get install elasticsearch

# Enable with auto start
sudo systemctl enable elasticsearch
sudo systemctl start elasticsearch
