#!/usr/bin/env bash

git clone --depth=1 https://github.com/vim/vim.git "$HOME"/vim
cd "$HOME"/vim || return
./configure \
    --with-features=huge
make
# Check if using Blink Build if not install normally
if [ -f /.dockerenv ]; then
    make install
    cd && rm -rfv "$HOME"/vim
else
    sudo make install
    cd && sudo rm -rfv "$HOME"/vim
fi
