#!/usr/bin/env bash

DATE="2021-07-28-a"
SYSTEM="ubuntu2004"
VERSION="ubuntu20.04"
BRANCH="swift-5.5-branch"
SNAP="swift-5.5-DEVELOPMENT-SNAPSHOT-"
PKG=$SNAP$DATE-$VERSION

wget https://swift.org/builds/$BRANCH/$SYSTEM/$SNAP$DATE/$PKG.tar.gz

if [ -f /.dockerenv ]; then
    tar -C "$HOME/" -xzf "$PKG.tar.gz"
    rm -rfi "$PKG.tar.gz"
else
    sudo tar -C "$HOME/.swift" -xzf "$PKG.tar.gz"
    sudo rm -rfi "$PKG.tar.gz"
fi

mv "$HOME/$PKG" "$HOME/.swift"
