#!/usr/bin/env bash

VERSION="2.3.0"

wget https://github.com/cli/cli/releases/download/v"$VERSION"/gh_"$VERSION"_linux_amd64.deb
sudo dpkg -i gh_"$VERSION"_linux_amd64.deb
# rm -rf gh_"$VERSION"_linux_amd64.deb

gh auth login
